network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
  # wifis:
  #   wlan0:
  #     dhcp4: true
  #     dhcp4-overrides:
  #       use-dns: no
  #     nameservers:
  #       - 127.0.0.53
  #     access-points:
  #       YOUR_ACCESS_POINT:
  #         password: WIFI_PASSWORD
